language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php -S localhost:8000 
  - sleep 3

script: 
  - phpunit
  - ./vendor/bin/behat --config app/tests/behat.yml

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
